parameters:
#    tlt_admn.example.class: Tlt\AdmnBundle\Example

services:
#    tlt_admn.example:
#        class: %tlt_admn.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]